functionsDirectory = "C:\\Users\\Ben\\Desktop\\Friday_Ben_Lynch_v1\\netlify\\functions"
functionsDirectoryOrigin = "config"
headers = []
redirects = []

[functions]

[functions."*"]

[[plugins]]
origin = "config"
package = "@netlify/plugin-nextjs"

[plugins.inputs]

[build]
publish = "C:\\Users\\Ben\\Desktop\\Friday_Ben_Lynch_v1\\.next"
publishOrigin = "config"
commandOrigin = "config"
command = "npm run build"
functions = "C:\\Users\\Ben\\Desktop\\Friday_Ben_Lynch_v1\\netlify\\functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]